name: Windows-RDP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extrair ngrok
      run: Expand-Archive ngrok.zip -DestinationPath .

    - name: Iniciar ngrok
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN; .\ngrok.exe tcp 3389 > ngrok.log &
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Esperar ngrok
      run: Start-Sleep -Seconds 15

    - name: Obter link do túnel
      run: |
        $url = Invoke-WebRequest -UseBasicParsing http://127.0.0.1:4040/api/tunnels | ConvertFrom-Json
        $publicUrl = $url.tunnels[0].public_url
        Write-Output "Ngrok Tunnel: $publicUrl"
