# This is a basic workflow to help you get started with Actions

name: Windows

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: gautamkrishnar/keepalive-workflow@1.0.9
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: keep alive
      run: ./keepalive2.ps1
